sudo: required
services:
    - docker
before_install:
    - docker pull ubuntu:18.04
    - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/home/gdbus-codegen-glibmm -td ubuntu:18.04 /bin/bash
    - docker exec -ti travis-ci bash -c "apt-get -qq update"
    - docker exec -ti travis-ci bash -c "apt-get install -y cmake dbus-test-runner diffutils libglibmm-2.4-dev python3-pytest python3-setuptools python3-jinja2"
install:
    - docker exec -ti travis-ci bash -c "cd /home/gdbus-codegen-glibmm && python3 ./setup.py install"
script:
    - docker exec travis-ci bash -c "cd /home/gdbus-codegen-glibmm/tests/ && pytest-3 -vv"
    - docker exec travis-ci bash -c "cd /home/gdbus-codegen-glibmm/tests/integration && dbus-test-runner -t ./runtests.sh"
after_script:
    - docker stop travis-ci
