sudo: required
services:
    - docker
before_install:
    - docker pull ubuntu:18.04
    - docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/home/gdbus-codegen-glibmm -td ubuntu:18.04 /bin/bash
    - docker exec -ti travis-ci bash -c "apt-get -qq update"
    - docker exec -ti travis-ci bash -c "apt-get install -y cmake dbus-test-runner libglibmm-2.4-dev python-setuptools"
install:
    - docker exec -ti travis-ci bash -c "cd /home/gdbus-codegen-glibmm && python2.7 ./setup.py install"
script:
    - docker exec travis-ci bash -c "cd /home/gdbus-codegen-glibmm/test && dbus-test-runner -t ./runtests.sh"
after_script:
    - docker stop travis-ci
