language: python
python:
    - "2.7"
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libglibmm-2.4-dev
install:
    - python ./setup.py install
script:
    - cd test && ./runtests.sh
